spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        default_batch_fetch_size: 1000
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:/db/migration

logging:
  level:
    org.springframework.jdbc.core: trace
