spring:
  jpa:
    open-in-view: false

kafka:
  topics:
    order-created: order-created
    reply-order-created: reply-order-created
    order-table-changed-empty: order-table-changed-empty
    table-ungrouped: table-ungrouped
    order-uncompleted: order-uncompleted
    orders-uncompleted: orders-uncompleted

module:
  product:
    url: http://127.0.0.1:8081
    list:
      path: /api/products
      method: GET
    create:
      path: /api/products
      method: POST
  menu:
    url: http://127.0.0.1:8082
    list:
      path: /api/menus
      method: GET
  table:
    url: http://127.0.0.1:8083
  order:
    url: http://127.0.0.1:8084
    find:
      path: /api/orders/{id}
      method: GET

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.jdbc.core: trace
    org.hibernate.type.descriptor.sql: trace

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.jdbc.core: trace
    org.hibernate.type.descriptor.sql: trace

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
